In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(123)

In [32]:
# create a dataframe with two classes
total_samples=1000
class_0_ratio=0.9
sample_0=int(total_samples*class_0_ratio)
sample_1=total_samples-sample_0

In [14]:
sample_0,sample_1

(900, 100)

In [17]:
# create my dataframe with imbalance dataset

class_0=pd.DataFrame({
    'feature1':np.random.normal(loc=0, scale=1, size=sample_0),
    'feature2':np.random.normal(loc=0, scale=1, size=sample_0),
    'target':[0]*sample_0
})
class_1=pd.DataFrame({
    'feature1':np.random.normal(loc=2, scale=1, size=sample_1),
    'feature2':np.random.normal(loc=2, scale=1, size=sample_1),
    'target':[1]*sample_1
})

In [18]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [20]:
df.tail()

     feature1  feature2  target
995  2.212564  2.509119       1
996  2.573401  0.842369       1
997  1.495319  2.329854       1
998  1.646934  3.353429       1
999  1.317452  1.791169       1

In [21]:
df.head()

   feature1  feature2  target
0 -1.548223  0.503020       0
1  0.228437  0.702123       0
2 -0.455654  0.473973       0
3 -0.286088 -0.993136       0
4  0.610811  0.887920       0

In [22]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

### Upsampling

In [23]:
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [36]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority,replace=True,
                                n_samples=len(df_majority),
                                random_state=42)

In [42]:
df_minority_upsampled.shape

(900, 3)

In [39]:
df_minority_upsampled.head()

     feature1  feature2  target
951  1.517849  3.427021       1
992  1.202480  1.883951       1
914  0.807986  1.416201       1
971  1.898712  0.143773       1
960  2.022862  2.061432       1

In [45]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [46]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

### Down sampling

In [48]:
import numpy as np
import pandas as pd

np.random.seed(123)

total_samples=1000
class_0_ratio=0.9
sample_0=int(total_samples*class_0_ratio)
sample_1=total_samples-sample_0

sample_0,sample_1

class_0=pd.DataFrame({
    'feature1':np.random.normal(loc=0, scale=1, size=sample_0),
    'feature2':np.random.normal(loc=0, scale=1, size=sample_0),
    'target':[0]*sample_0
})
class_1=pd.DataFrame({
    'feature1':np.random.normal(loc=2, scale=1, size=sample_1),
    'feature2':np.random.normal(loc=2, scale=1, size=sample_1),
    'target':[1]*sample_1
})

df=pd.concat([class_0,class_1]).reset_index(drop=True)

df.tail()

df.head()

df['target'].value_counts()

df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

from sklearn.utils import resample
df_majority_downsampled=resample(df_majority,replace=True,
                                n_samples=len(df_minority),
                                random_state=42)

df_majority_downsampled.shape

df_majority_downsampled.head()

df_downsampled=pd.concat([df_minority,df_majority_downsampled])

df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64